name: Lint Commit Messages
on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: wagoid/commitlint-github-action@v5