name: Lint Commit Messages
on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Install
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm install
      - run: npx commitlint --from HEAD~${{ github.event.pull_request.commits }} --to HEAD --verbose
      # - run: git log -1 --pretty=format:"%s" | npx commitlint --verbose
      