name: Lint Commit Messages
on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm install
      - run: npx commitlint --from HEAD~1 --to HEAD --verbose
      